//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hl7.Fhir.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hl7.Fhir.Api.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; is null or empty..
        /// </summary>
        internal static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only deserialize resources and complex model classes, not &apos;{0}&apos;.
        /// </summary>
        internal static string CanOnlyDeserializeResourceAndComplex {
            get {
                return ResourceManager.GetString("CanOnlyDeserializeResourceAndComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only deserialize typed collections: type &apos;{0}&apos; is neither an array, nor does it implement IEnumerable&lt;T&gt;.
        /// </summary>
        internal static string CanOnlyDeserializeTypedCollections {
            get {
                return ResourceManager.GetString("CanOnlyDeserializeTypedCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to deserialize (data is null).
        /// </summary>
        internal static string DataToDeserializeNull {
            get {
                return ResourceManager.GetString("DataToDeserializeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unknown member &apos;{0}&apos; while deserializing.
        /// </summary>
        internal static string DeserializeUnknownMember {
            get {
                return ResourceManager.GetString("DeserializeUnknownMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory failed to create object.
        /// </summary>
        internal static string FactoryCreationFailed {
            get {
                return ResourceManager.GetString("FactoryCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ModelClassFactory registered to handle type &apos;{0}&apos;.
        /// </summary>
        internal static string NoSuchClassFactory {
            get {
                return ResourceManager.GetString("NoSuchClassFactory", resourceCulture);
            }
        }
    }
}
