// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1

using Hl7.Fhir.Serialization.Poco;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, 
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this 
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, 
     this list of conditions and the following disclaimer in the documentation 
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
  POSSIBILITY OF SUCH DAMAGE.
  
*/

namespace Hl7.Fhir.Serialization
{
    /// <summary>
    /// Default JsonSerializerOptions to format JSON serialization as expected.
    /// </summary>
    public static class FhirSerializerOptions
  {
    /// <summary>
    /// Debug option for serialiation / parsing.
    /// </summary>
public static bool Debug { get; set; } = false;
#pragma warning disable CA1810 // Initialize reference type static fields inline

    /// <summary>
    /// Converters list for use in options.
    /// </summary>
    private static readonly List<JsonConverter> _converters;

    /// <summary>
    /// Serializer options for deserialization, or serializing in Compact format.
    /// </summary>
    private static readonly JsonSerializerOptions _serializerCompact;

    /// <summary>
    /// Serializer options for deserialization, or serializing in Pretty format.
    /// </summary>
    private static readonly JsonSerializerOptions _serializerPretty;

    /// <summary>
    /// Writer options for Compact format writing.
    /// </summary>
    private static readonly JsonWriterOptions _writerCompact;

    /// <summary>
    /// Writer options for Pretty format writing.
    /// </summary>
    private static readonly JsonWriterOptions _writerPretty;

    /// <summary>
    /// Initializes static members of the &lt;see cref="FhirSerializerOptions"/&gt; class.
    /// </summary>
    static FhirSerializerOptions()
    {
      _converters = new List<JsonConverter>()
      {
        new JsonStreamResourceConverter(),
      };

      _serializerCompact = new JsonSerializerOptions()
      {
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        WriteIndented = false,
      };

      _serializerPretty = new JsonSerializerOptions()
      {
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        WriteIndented = true,
      };

      foreach (JsonConverter converter in _converters)
      {
        _serializerCompact.Converters.Add(converter);
        _serializerPretty.Converters.Add(converter);
      }

      _writerCompact = new JsonWriterOptions()
      {
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        Indented = false,
      };

      _writerPretty = new JsonWriterOptions()
      {
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        Indented = true,
      };

    }
#pragma warning restore CA1810 // Initialize reference type static fields inline

    /// <summary>
    /// Converters list for polymorphic deserialization (use in options).
    /// </summary>
    public static List<JsonConverter> FhirConverters => _converters;

    /// <summary>
    /// Serializer options for deserialization, or serializing in Compact format.
    /// </summary>
    public static JsonSerializerOptions SerializerCompact => _serializerCompact;

    /// <summary>
    /// Serializer options for deserialization, or serializing in Pretty format.
    /// </summary>
    public static JsonSerializerOptions SerializerPretty => _serializerPretty;

    /// <summary>
    /// Writer options for Compact format writing.
    /// </summary>
    public static JsonWriterOptions WriterCompact => _writerCompact;

    /// <summary>
    /// Writer options for Pretty format writing.
    /// </summary>
    public static JsonWriterOptions WriterPretty => _writerPretty;
  }
}
// end of file
