//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hl7.Fhir.Serialization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hl7.Fhir.Serialization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; targetNamespace=&quot;http://www.w3.org/1999/xhtml&quot; elementFormDefault=&quot;qualified&quot; version=&quot;1.0&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt;!--
        ///  FHIR XHTML Schema
        ///  
        ///  This is a pared down modification of the XHTML schema published by the W3C. 
        ///  it does not allow any of the content that the FHIR specification bans. 
        ///  
        ///  Note that you can replace this schema with the standard W3C schema - this 
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fhir_xhtml {
            get {
                return ResourceManager.GetString("fhir_xhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;?xml-stylesheet href=&quot;../2008/09/xsd.xsl&quot; type=&quot;text/xsl&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt;!-- Note: When using this schema with some tools, it may also be necessary to declare xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;, however this causes performance issues with other tools and thus is not in the base schemas. --&gt;
        ///  &lt;xs:annotation&gt;
        ///    &lt;xs: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xml {
            get {
                return ResourceManager.GetString("xml", resourceCulture);
            }
        }
    }
}
