<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\firely-net-sdk-tests.props" />

	<PropertyGroup>
		<AssemblyName>Hl7.Fhir.Support.Tests</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Update="MSTest.TestFramework" Version="4.2.3" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Hl7.Fhir.Base\Hl7.Fhir.Base.csproj" />
	</ItemGroup>

</Project>
