//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hl7.Fhir.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hl7.Fhir.Properties.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;resourceType&quot;: &quot;Patient&quot;,
        ///    &quot;identifier&quot;: [{
        ///        &quot;label&quot;: &quot;MRN&quot;,
        ///        &quot;period&quot;: {&quot;start&quot;: &quot;2001-05-06&quot;},
        ///        &quot;assigner&quot;: {&quot;display&quot;: &quot;Acme\u202fHealthcare&quot;},
        ///        &quot;use&quot;: &quot;usual&quot;,
        ///        &quot;system&quot;: &quot;urn:oid:1.2.36.146.595.217.0.1&quot;,
        ///        &quot;value&quot;: &quot;12345&quot;
        ///    }],
        ///    &quot;managingOrganization&quot;: {&quot;reference&quot;: &quot;Organization/1&quot;},
        ///    &quot;_active&quot;: {&quot;extension&quot;: [{
        ///        &quot;url&quot;: &quot;http://hl7.org/fhir/example-do-not-use#recordStatus&quot;,
        ///        &quot;valueCode&quot;: &quot;archived&quot;
        ///    }]},
        ///    &quot;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestPatientJson {
            get {
                return ResourceManager.GetString("TestPatientJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;resourceType&quot;: &quot;Patient&quot;,
        ///   
        ///    &quot;contained&quot;: [
        ///        {
        ///            &quot;resourceType&quot;: &quot;Binary&quot;,
        ///            &quot;id&quot;: &quot;pic1&quot;,
        ///            &quot;contentType&quot;: &quot;image/gif&quot;,
        ///            &quot;content&quot;: &quot;R0lGODlhEwARAPcAAAAAAAAA/+9aAO+1AP/WAP/eAP/eCP/eEP/eGP/nAP/nCP/nEP/nIf/nKf/nUv/nWv/vAP/vCP/vEP/vGP/vIf/vKf/vMf/vOf/vWv/vY//va//vjP/3c//3lP/3nP//tf//vf//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestPatientLargeNumbers {
            get {
                return ResourceManager.GetString("TestPatientLargeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/example-do-not-use#Patient.avatar&quot;&gt;
        ///    &lt;valueResource&gt;
        ///      &lt;reference value=&quot;#pic1&quot;/&gt;
        ///      &lt;display value=&quot;Duck image&quot;/&gt;
        ///    &lt;/valueResource&gt;
        ///  &lt;/extension&gt;
        ///  &lt;extension url=&quot;urn:example-do-not-use:pi&quot;&gt;
        ///    &lt;valueDecimal value=&quot;3.141592653589793&quot;/&gt;
        ///  &lt;/extension&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;generated&quot;/&gt;
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      &lt;table&gt;
        ///        &lt;tbo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestPatientXml {
            get {
                return ResourceManager.GetString("TestPatientXml", resourceCulture);
            }
        }
    }
}
