name: Add isuses to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with: 
          project-url: https://github.com/orgs/FirelyTeam/projects/6
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}